[package]
name = "system"
version.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"

[dependencies]
dirs = "5.0.1"
sha2 = "0.10.9"
reqwest = { version = "0.13", features = ["rustls"] }

