[workspace]
members = ["core", "frontend", "sources", "util"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[package]
name = "still"
version.workspace = true
edition.workspace = true

[dependencies]
core = { path = "core" }
frontend = { path = "frontend" }
sources = { path = "sources" }
util = { path = "util" }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
