[package]
name = "still"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
ratatui = "0.30.0"
color-eyre = "0.6.5"
crossterm = "0.29.0"
semver = "1.0.27"
reqwest = { version = "0.12.28", features = [
  "json",
  "gzip",
  "brotli",
  "deflate",
  "rustls-tls",
] }
tokio = { version = "1.48.0", features = ["full"] }
toml = "0.9.8"
mlua = { version = "0.11.5", features = ["luajit"] }
serde_json = "1.0.148"
serde = { version = "1.0.228", features = ["derive"] }
futures-util = "0.3.31"
fuzzy-matcher = "0.3.7"

[profile.release]
strip = true      # Automatically strip symbols from the binary.
opt-level = "z"   # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"
